// See LICENSE for license details.
#include <stdint.h>


#include <platform.h>

#include "common.h"

#define DEBUG
//#define DYNAMIC_SWITCH_CLK
#define SOC_IRAM_MAX_SIZE 0x200   // 1M
#define PRINT_INFO_INDENT (SOC_IRAM_MAX_SIZE>>2)

#include "kprintf.h"

#include "nvdla.h"

#define NVDLA_BASE 0x53000000UL
// #define reg_write(addr,val) reg_write32(NVDLA_BASE+addr,val)
// #define reg_read(addr) reg_read32(NVDLA_BASE+addr)

// #define reg_write(addr, val) _REG32(NVDLA_BASE, (addr))=(val)
// #define reg_read(addr) _REG32(NVDLA_BASE, (addr))



int main(void) {

  uint32_t pass_flag;
  register int check_idx;
  //uint32_t * ddr_ptr;
  //uint32_t *pcie_lsys_ptr;
  //unsigned long test;
  //test = 0x5a5a;
  //uint64_t test_addr[9];
  //uint64_t base_addr;
  //uint64_t incr_addr;
  //uint32_t *test_ptr;
  // uint64_t *test_ptr_64;
  // uint64_t temp_data;
  // uint64_t dut_data;
  // uint32_t temp_data_32;
  // uint64_t soc_iram_max_size_64 = SOC_IRAM_MAX_SIZE ;

  // // test_addr[0] = 0x60000000UL;   // failed
  // // test_addr[0] = 0x40000000UL;   // failed
  // test_addr[0] = 0xa8000000UL;   //
  // // test_addr[1] = 0x08000000UL;   // failed
  // test_addr[1] = 0x88000000UL;   // ddr
  // test_addr[2] = 0x02000000UL;   // clint
  // //test_addr[3] = 0x00002000UL;   // gpio failed
  // test_addr[3] = 0xa0002000UL;   //  
  // test_addr[4] = 0xb2000000UL;   // ddr
  // //test_addr[5] = 0xc3000000UL;   // ddr failed
  // test_addr[5] = 0x99000000UL;
  // test_addr[6] = 0x50000000UL;   // soc iram
  // test_addr[7] = 0x52000000UL;   //  spi_1
  // test_addr[8] = 0x2000000000UL;   // pcie slave timeout
  // //test_addr[7] = 0x51000008UL;   //  lsys donnot access , maybe access control register
  
  //REG32(uart, UART_REG_DIV) = 271;  // 
  REG32(uart, UART_REG_DIV) = 1;
  REG32(uart, UART_REG_RXCTRL) = UART_TXEN;
  REG32(uart, UART_REG_TXCTRL) = UART_RXEN;  // donot delete


  kprintf("Test begin ! @ core: 0x%x, compiler date: %s, time: %s", read_csr(mhartid), __DATE__,__TIME__);

  _REG32(_AC(0x51000000, UL), 0x100) = (0x0 << 31) + (0x3 << 29) + (0x3 << 23) + (0x2 << 20) + (0x1 << 18);  
  // wait more than 1us
  // check pll lock 100 times
	for(int i = 1; i >= 0; i--) {
		kprintf("Info: test pll state index: 0x%x - 0x%x", i, _REG32(_AC(0x51000000, UL), 0x20));
	}
  _REG32(_AC(0x51000000, UL), 0x18) = (0x1 << 15) + (0x1 << 10) + (0x1 << 5) + (0x1);  // SOC_LSYS cfg pll cfg, use pll output default clk
	
  //test_nvdla();
	_REG32(_AC(0x51000000, UL), 0x30) = (0x1 << 31) + (0x1 << 30) + (0x1 << 17) + (0x1 << 16) + (0x0 << 1) + (0x0 << 0);
	kprintf("Info: release nvdla ip rst 0x%x", _REG32(_AC(0x51000000, UL), 0x30));


    //----------## Layer:CDP_0: cross layer dependency, begin----------
    //----------## Layer:CDP_0: cross layer dependency, end----------
    //----------## Layer:CDP_0: set producer pointer, begin----------
    _REG32(NVDLA_BASE, CDP_S_POINTER_0) = 0x0;
    _REG32(NVDLA_BASE, CDP_RDMA_S_POINTER_0) = 0x0;
    //----------## Layer:CDP_0: set producer pointer, end----------
    //----------## Layer:CDP_0: LUT programming, begin----------
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_CFG_0) = 0x30000;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x0;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x1;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x2;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x3;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x4;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x5;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x6;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x7;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x8;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x9;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xa;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xb;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xc;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xd;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xe;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xf;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x10;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x11;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x12;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x13;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x14;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x15;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x16;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x17;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x18;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x19;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x1a;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x1b;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x1c;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x1d;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x1e;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x1f;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x20;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x21;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x22;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x23;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x24;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x25;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x26;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x27;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x28;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x29;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x2a;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x2b;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x2c;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x2d;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x2e;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x2f;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x30;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x31;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x32;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x33;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x34;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x35;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x36;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x37;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x38;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x39;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x3a;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x3b;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x3c;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x3d;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x3e;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x3f;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x40;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x41;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x42;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x43;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x44;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x45;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x46;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x47;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x48;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x49;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x4a;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x4b;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x4c;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x4d;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x4e;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x4f;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x50;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x51;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x52;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x53;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x54;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x55;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x56;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x57;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x58;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x59;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x5a;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x5b;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x5c;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x5d;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x5e;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x5f;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x60;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x61;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x62;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x63;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x64;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x65;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x66;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x67;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x68;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x69;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x6a;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x6b;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x6c;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x6d;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x6e;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x6f;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x70;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x71;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x72;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x73;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x74;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x75;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x76;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x77;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x78;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x79;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x7a;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x7b;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x7c;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x7d;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x7e;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x7f;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x80;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x81;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x82;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x83;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x84;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x85;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x86;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x87;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x88;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x89;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x8a;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x8b;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x8c;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x8d;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x8e;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x8f;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x90;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x91;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x92;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x93;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x94;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x95;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x96;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x97;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x98;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x99;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x9a;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x9b;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x9c;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x9d;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x9e;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x9f;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xa0;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xa1;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xa2;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xa3;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xa4;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xa5;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xa6;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xa7;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xa8;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xa9;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xaa;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xab;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xac;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xad;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xae;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xaf;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xb0;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xb1;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xb2;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xb3;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xb4;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xb5;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xb6;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xb7;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xb8;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xb9;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xba;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xbb;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xbc;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xbd;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xbe;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xbf;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xc0;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xc1;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xc2;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xc3;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xc4;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xc5;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xc6;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xc7;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xc8;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xc9;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xca;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xcb;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xcc;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xcd;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xce;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xcf;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xd0;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xd1;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xd2;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xd3;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xd4;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xd5;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xd6;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xd7;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xd8;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xd9;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xda;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xdb;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xdc;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xdd;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xde;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xdf;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xe0;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xe1;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xe2;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xe3;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xe4;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xe5;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xe6;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xe7;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xe8;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xe9;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xea;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xeb;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xec;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xed;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xee;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xef;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xf0;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xf1;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xf2;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xf3;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xf4;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xf5;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xf6;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xf7;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xf8;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xf9;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xfa;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xfb;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xfc;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xfd;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xfe;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xff;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x100;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_CFG_0) = 0x20000;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x0;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x1;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x2;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x3;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x4;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x5;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x6;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x7;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x8;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x9;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xa;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xb;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xc;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xd;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xe;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0xf;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x10;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x11;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x12;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x13;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x14;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x15;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x16;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x17;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x18;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x19;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x1a;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x1b;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x1c;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x1d;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x1e;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x1f;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x20;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x21;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x22;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x23;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x24;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x25;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x26;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x27;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x28;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x29;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x2a;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x2b;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x2c;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x2d;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x2e;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x2f;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x30;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x31;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x32;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x33;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x34;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x35;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x36;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x37;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x38;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x39;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x3a;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x3b;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x3c;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x3d;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x3e;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x3f;
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x40;
    _REG32(NVDLA_BASE, CDP_S_LUT_LE_START_LOW_0) = 0x0;
    // CDP_S_LUT_LE_START_LOW_0.LUT_LE_START_LOW:0x0
    _REG32(NVDLA_BASE, CDP_S_LUT_LO_END_LOW_0) = 0x100;
    // CDP_S_LUT_LO_END_LOW_0.LUT_LO_END_LOW:0x100
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_CFG_0) = 0x0;
    // CDP_S_LUT_ACCESS_CFG_0.LUT_ACCESS_TYPE:READ : 0x0
    // CDP_S_LUT_ACCESS_CFG_0.LUT_TABLE_ID:LE : 0x0
    // CDP_S_LUT_ACCESS_CFG_0.LUT_ADDR:0x0
    _REG32(NVDLA_BASE, CDP_S_LUT_ACCESS_DATA_0) = 0x0;
    // CDP_S_LUT_ACCESS_DATA_0.LUT_DATA:0x0
    _REG32(NVDLA_BASE, CDP_S_LUT_LE_START_HIGH_0) = 0x0;
    // CDP_S_LUT_LE_START_HIGH_0.LUT_LE_START_HIGH:0x0
    _REG32(NVDLA_BASE, CDP_S_LUT_LO_END_HIGH_0) = 0x0;
    // CDP_S_LUT_LO_END_HIGH_0.LUT_LO_END_HIGH:0x0
    _REG32(NVDLA_BASE, CDP_S_LUT_CFG_0) = 0x1;
    // CDP_S_LUT_CFG_0.LUT_UFLOW_PRIORITY:LE : 0x0
    // CDP_S_LUT_CFG_0.LUT_OFLOW_PRIORITY:LE : 0x0
    // CDP_S_LUT_CFG_0.LUT_HYBRID_PRIORITY:LE : 0x0
    // CDP_S_LUT_CFG_0.LUT_LE_FUNCTION:LINEAR : 0x1
    _REG32(NVDLA_BASE, CDP_S_LUT_LE_SLOPE_SHIFT_0) = 0x0;
    // CDP_S_LUT_LE_SLOPE_SHIFT_0.LUT_LE_SLOPE_OFLOW_SHIFT:0x0
    // CDP_S_LUT_LE_SLOPE_SHIFT_0.LUT_LE_SLOPE_UFLOW_SHIFT:0x0
    _REG32(NVDLA_BASE, CDP_S_LUT_LE_SLOPE_SCALE_0) = 0x0;
    // CDP_S_LUT_LE_SLOPE_SCALE_0.LUT_LE_SLOPE_UFLOW_SCALE:0x0
    // CDP_S_LUT_LE_SLOPE_SCALE_0.LUT_LE_SLOPE_OFLOW_SCALE:0x0
    _REG32(NVDLA_BASE, CDP_S_LUT_INFO_0) = 0x0;
    // CDP_S_LUT_INFO_0.LUT_LE_INDEX_SELECT:0x0
    // CDP_S_LUT_INFO_0.LUT_LE_INDEX_OFFSET:0x0
    // CDP_S_LUT_INFO_0.LUT_LO_INDEX_SELECT:0x0
    _REG32(NVDLA_BASE, CDP_S_LUT_LE_END_LOW_0) = 0x40;
    // CDP_S_LUT_LE_END_LOW_0.LUT_LE_END_LOW:0x40
    _REG32(NVDLA_BASE, CDP_S_LUT_LO_SLOPE_SCALE_0) = 0x0;
    // CDP_S_LUT_LO_SLOPE_SCALE_0.LUT_LO_SLOPE_OFLOW_SCALE:0x0
    // CDP_S_LUT_LO_SLOPE_SCALE_0.LUT_LO_SLOPE_UFLOW_SCALE:0x0
    _REG32(NVDLA_BASE, CDP_S_LUT_LE_END_HIGH_0) = 0x0;
    // CDP_S_LUT_LE_END_HIGH_0.LUT_LE_END_HIGH:0x0
    _REG32(NVDLA_BASE, CDP_S_LUT_LO_START_HIGH_0) = 0x0;
    // CDP_S_LUT_LO_START_HIGH_0.LUT_LO_START_HIGH:0x0
    _REG32(NVDLA_BASE, CDP_S_LUT_LO_START_LOW_0) = 0x0;
    // CDP_S_LUT_LO_START_LOW_0.LUT_LO_START_LOW:0x0
    _REG32(NVDLA_BASE, CDP_S_LUT_LO_SLOPE_SHIFT_0) = 0x0;
    // CDP_S_LUT_LO_SLOPE_SHIFT_0.LUT_LO_SLOPE_UFLOW_SHIFT:0x0
    // CDP_S_LUT_LO_SLOPE_SHIFT_0.LUT_LO_SLOPE_OFLOW_SHIFT:0x0
    //----------## Layer:CDP_0: LUT programming, end----------
    //----------## Layer:CDP_0: configuraion, begin----------
    _REG32(NVDLA_BASE, CDP_D_DATOUT_OFFSET_0) = 0x80;
    // CDP_D_DATOUT_OFFSET_0.DATOUT_OFFSET:0x80
    _REG32(NVDLA_BASE, CDP_D_DST_SURFACE_STRIDE_0) = 0x800;
    // CDP_D_DST_SURFACE_STRIDE_0.DST_SURFACE_STRIDE:0x40
    _REG32(NVDLA_BASE, CDP_RDMA_D_SRC_BASE_ADDR_LOW_0) = 0x90000000;
    // CDP_RDMA_D_SRC_BASE_ADDR_LOW_0.SRC_BASE_ADDR_LOW:0x4000000
    _REG32(NVDLA_BASE, CDP_D_DST_DMA_CFG_0) = 0x1;
    // CDP_D_DST_DMA_CFG_0.DST_RAM_TYPE:MC : 0x1
    _REG32(NVDLA_BASE, CDP_RDMA_D_DATA_CUBE_WIDTH_0) = 0x7;
    // CDP_RDMA_D_DATA_CUBE_WIDTH_0.WIDTH:0x7
    _REG32(NVDLA_BASE, CDP_RDMA_D_DATA_FORMAT_0) = 0x0;
    // CDP_RDMA_D_DATA_FORMAT_0.INPUT_DATA:INT8 : 0x0
    _REG32(NVDLA_BASE, CDP_D_DATIN_SCALE_0) = 0x1;
    // CDP_D_DATIN_SCALE_0.DATIN_SCALE:0x1
    _REG32(NVDLA_BASE, CDP_D_DATOUT_SHIFTER_0) = 0x0;
    // CDP_D_DATOUT_SHIFTER_0.DATOUT_SHIFTER:0x0
    _REG32(NVDLA_BASE, CDP_D_CYA_0) = 0x0;
    // CDP_D_CYA_0.CYA:0x0
    _REG32(NVDLA_BASE, CDP_RDMA_D_PERF_ENABLE_0) = 0x0;
    // CDP_RDMA_D_PERF_ENABLE_0.DMA_EN:DISABLE : 0x0
    _REG32(NVDLA_BASE, CDP_D_LRN_CFG_0) = 0x0;
    // CDP_D_LRN_CFG_0.NORMALZ_LEN:LEN3 : 0x0
    _REG32(NVDLA_BASE, CDP_RDMA_D_DATA_CUBE_CHANNEL_0) = 0x1f;
    // CDP_RDMA_D_DATA_CUBE_CHANNEL_0.CHANNEL:0x1f
    _REG32(NVDLA_BASE, CDP_D_DATA_FORMAT_0) = 0x0;
    // CDP_D_DATA_FORMAT_0.INPUT_DATA_TYPE:INT8 : 0x0
    _REG32(NVDLA_BASE, CDP_D_DATIN_SHIFTER_0) = 0x0;
    // CDP_D_DATIN_SHIFTER_0.DATIN_SHIFTER:0x0
    _REG32(NVDLA_BASE, CDP_D_PERF_ENABLE_0) = 0x0;
    // CDP_D_PERF_ENABLE_0.LUT_EN:DISABLE : 0x0
    // CDP_D_PERF_ENABLE_0.DMA_EN:DISABLE : 0x0
    _REG32(NVDLA_BASE, CDP_RDMA_D_SRC_BASE_ADDR_HIGH_0) = 0x0;
    // CDP_RDMA_D_SRC_BASE_ADDR_HIGH_0.SRC_BASE_ADDR_HIGH:0x0
    _REG32(NVDLA_BASE, CDP_D_DST_BASE_ADDR_HIGH_0) = 0x0;
    // CDP_D_DST_BASE_ADDR_HIGH_0.DST_BASE_ADDR_HIGH:0x0
    _REG32(NVDLA_BASE, CDP_RDMA_D_SRC_DMA_CFG_0) = 0x1;
    // CDP_RDMA_D_SRC_DMA_CFG_0.SRC_RAM_TYPE:MC : 0x1
    _REG32(NVDLA_BASE, CDP_D_DATOUT_SCALE_0) = 0x1;
    // CDP_D_DATOUT_SCALE_0.DATOUT_SCALE:0x1
    _REG32(NVDLA_BASE, CDP_D_DATIN_OFFSET_0) = 0x80;
    // CDP_D_DATIN_OFFSET_0.DATIN_OFFSET:0x80
    _REG32(NVDLA_BASE, CDP_D_NAN_FLUSH_TO_ZERO_0) = 0x0;
    // CDP_D_NAN_FLUSH_TO_ZERO_0.NAN_TO_ZERO:DISABLE : 0x0
    _REG32(NVDLA_BASE, CDP_D_FUNC_BYPASS_0) = 0x3;
    // CDP_D_FUNC_BYPASS_0.SQSUM_BYPASS:ENABLE : 0x1
    // CDP_D_FUNC_BYPASS_0.MUL_BYPASS:ENABLE : 0x1
    _REG32(NVDLA_BASE, CDP_D_DST_BASE_ADDR_LOW_0) = 0x90080000;
    // CDP_D_DST_BASE_ADDR_LOW_0.DST_BASE_ADDR_LOW:0x4004000
    _REG32(NVDLA_BASE, CDP_RDMA_D_CYA_0) = 0x0;
    // CDP_RDMA_D_CYA_0.CYA:0x0
    _REG32(NVDLA_BASE, CDP_RDMA_D_SRC_SURFACE_STRIDE_0) = 0x800;
    // CDP_RDMA_D_SRC_SURFACE_STRIDE_0.SRC_SURFACE_STRIDE:0x40
    _REG32(NVDLA_BASE, CDP_D_DST_LINE_STRIDE_0) = 0x100;
    // CDP_D_DST_LINE_STRIDE_0.DST_LINE_STRIDE:0x8
    _REG32(NVDLA_BASE, CDP_RDMA_D_SRC_LINE_STRIDE_0) = 0x100;
    // CDP_RDMA_D_SRC_LINE_STRIDE_0.SRC_LINE_STRIDE:0x8
    _REG32(NVDLA_BASE, CDP_RDMA_D_DATA_CUBE_HEIGHT_0) = 0x7;
    // CDP_RDMA_D_DATA_CUBE_HEIGHT_0.HEIGHT:0x7
    //----------## Layer:CDP_0: configuraion, end----------
    //----------## Layer:CDP_0: operation enable, begin----------
    //----------#### Layer:CDP_0: operation enable, block:NVDLA_CDP_RDMA, begin --
    _REG32(NVDLA_BASE, CDP_RDMA_D_OP_ENABLE_0) = 0x1;
    //----------#### Layer:CDP_0: operation enable, block:NVDLA_CDP_RDMA, end   --
    //----------#### Layer:CDP_0: operation enable, block:NVDLA_CDP, begin --
    _REG32(NVDLA_BASE, CDP_D_OP_ENABLE_0) = 0x1;
    //----------#### Layer:CDP_0: operation enable, block:NVDLA_CDP, end   --
    //----------## Layer:CDP_0: operation enable, end----------

    register uint64_t cycle1 = rdcycle();
    
    kprintf("begin check nvdla glb_s_intr_status, cycle1: %x\n", cycle1);
    pass_flag = 0;
    for (check_idx = 0; check_idx < 32767; check_idx++) {
        if (_REG32(NVDLA_BASE, GLB_S_INTR_STATUS_0) != 0){
          pass_flag = 1;
          break;
        }
    }

    uint64_t cycle2 = rdcycle();
    //printf("cycle1: %lu, cycle2: %lu, diff: %lu\n", cycle1, cycle2, cycle2 - cycle1 );
    kprintf("cycle1: %x, cycle2: %x, diff: %x, check_idx: %x\n", cycle1, cycle2, cycle2 - cycle1, check_idx);



	kprintf("Test end ! @ core: 0x%x", read_csr(mhartid));

	if (pass_flag){
		kprintf("PASS");
	}
	else{
		kprintf("FAIL");
	}

	kprintf(SHUTDOWN_FLAG_STR);  // donnot delete

	return 0;
}

